news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('list-news', views.news_list, name="news_list"),
    path('detail-news/<int:id>', views.news_detail, name="news_detail"),
    path('create-news', views.news_create, name="news_create"),
    path('data-news', views.news_data, name="news_data"),
    path('submission-news', views.news_submission, name="news_submission"),
    path('detail/news/<int:id>', views.news_get_detail, name="news_get_detail"),
    path('login-pepew', views.loginPage, name="login"),
    path('register-pepew', views.registerPage, name="register"),
    path('logout-pepew', views.logoutUser, name="logout"),
]

virus_pepew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pepew_home.urls')),
    path('donate/', include('donasi.urls')),
    path('', include('news.urls')),
    path('', include('question.urls')),
    path('', include('rumah_sakit.urls')),
    path('', include('screening.urls')),
]

news/models.py
from django.db import models

# Create your models here.
class News(models.Model):
    title = models.CharField('Judul', max_length=255)
    source = models.CharField('Sumber', max_length=255)
    image_url = models.CharField('URL Gambar', max_length=255)
    content = models.TextField('Konten')
    date = models.DateTimeField(auto_now_add=True)

news/forms.py
from django.forms import ModelForm, TextInput, Textarea
from .models import News
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreateNews(ModelForm):
    class Meta:
        model = News
        fields = ['title', 'source', 'image_url', 'content']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'Lebih dari 5.000 Kasus Covid-19 dalam 2 Hari, Epidemiolog: Ini Belum yang Terburuk'}),
            'source': TextInput(attrs={'placeholder': 'https://www.kompas.com/'}),
            'image_url': TextInput(attrs={'placeholder': 'https://unsplash.com/'}),
            'content': Textarea(attrs={'placeholder': 'Tuliskan isi beritamu disini'})
        }

class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

news/views.py
from django.shortcuts import render, redirect
from .models import News
from .forms import CreateNews, RegisterForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.http import HttpResponse, JsonResponse

# Create your views here.
def news_data(request):
    news = News.objects.all().order_by('date')
    list_news = serializers.serialize('json', news)
    return HttpResponse(list_news, content_type="application/json")

@login_required(login_url='news:login')
def news_submission(request):
    if request.method == 'POST':
        form = CreateNews(request.POST)
        if form.is_valid():
            item = form.save()
            response_data = {
                'pk': item.pk,
                'title': item.title,
            }
            response = JsonResponse(response_data)
            response.status_code = 200
        else :
            response_data = {'error': form.errors}
            response = JsonResponse(response_data)
            response.status_code = 404
        return response
    response_data = {'error': 'Please try again later!'}
    response = JsonResponse(response_data)
    response.status_code = 404
    return response

def news_get_detail(request, id):
    item = News.objects.filter(pk = id)
    if item.exists():
        item =item[0]
        response_data = {
            'pk': item.pk,
            'title': item.title,
            'date': item.date,
            'source': item.source,
            'image_url': item.image_url,
            'content': item.content
        }
        response = JsonResponse(response_data)
        response.status_code = 200
        return response
    response_data = {'error': 'Berita tidak ditemukan!'}
    response = JsonResponse(response_data)
    response.status_code = 404
    return response

def news_list(request):
    return render(request, "pages/news-list.html")

def news_detail(request, id):
	#return detail of news
    return render(request, "pages/news-detail.html")

@login_required(login_url='news:login')
def news_create(request):
    form = CreateNews()
    return render(request, "pages/news-create.html", {'form' : form})

# Views for login
def loginPage(request):
    if request.user.is_authenticated:
        return redirect('pepew_home:home_url')
    else:
        html = 'user/login.html'
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username = username, password = password)

            if user is not None:
                login(request, user)
                return redirect(request.POST.get('next') or 'pepew_home:home_url')
            else:
                messages.info(request, 'Username or password is incorrect')
                return render(request, html)
        return render(request, html)

def registerPage(request):
    if request.user.is_authenticated:
        return redirect('pepew_home:home_url')
    else:
        form = RegisterForm(request.POST or None)

        if request.method == 'POST':
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('username')
                messages.success(request, 'Account was created for ' + user)
                return redirect('news:login')

        context = {'form' : form}
        html = 'user/register.html'
        return render(request, html, context)

def logoutUser(request):
    logout(request)
    return redirect('pepew_home:home_url')

news/templates/pages/news-create.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>Pepew | News</title>
{% endblock meta %}

{% block content %}
<main class="container">
    <h2 class="sub-title">Bagikan Berita Terbaru</h2>
    <form method="POST" id="form-news">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-group">
            <a class="btn pepew-button" href="{% url 'news:news_list' %}"><i class="fas fa-arrow-left"></i>Kembali</a>
            <input id="save-button" type="submit" value="Simpan" class="btn pepew-button" disabled=true>
        </div>
    </form>
</main>
{% endblock content %}

{% block script %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
<script src="{% static 'scripts/news-create.js' %}"></script>
{% endblock script %}

news/templates/pages/news-detail.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>Pepew | News</title>
{% endblock meta %}

{% block content %}
<main class="container"></main>
{% endblock content %}

{% block script %}
<script src="{% static 'scripts/news-detail.js' %}"></script>
{% endblock script %}

news/templates/pages/news-list.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{% static 'css/news.css' %}">
<title>Pepew | News</title>
{% endblock meta %}

{% block content %}
<div id="news-hero" class="hero">
    <h1>Berita</h1>
</div>

<main class="container">
    
    {% if user.is_authenticated %}
    <div id="question">
        <h2>Ingin menambahkan berita baru ?</h2>
        <div class="button-group">
            <a class="btn pepew-button" id="tulis" href="{% url 'news:news_create' %}">Tulis</a>
        </div>
    </div>
    {% endif %}
    <div id="news-grid"></div>
</main>
{% endblock content %}

{% block script %}
<script src="{% static 'scripts/news-list.js' %}"></script>
{% endblock script %}