news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('list-news', views.news_list, name="news_list"),
    path('detail-news/<int:id>', views.news_detail, name="news_detail"),
    path('create-news', views.news_create, name="news_create"),
    path('data-news', views.news_data, name="news_data"),
    path('submission-news', views.news_submission, name="news_submission"),
    path('detail/news/<int:id>', views.news_get_detail, name="news_get_detail"),
    path('login-pepew', views.loginPage, name="login"),
    path('register-pepew', views.registerPage, name="register"),
    path('logout-pepew', views.logoutUser, name="logout"),
]

rumah_sakit/urls.py
from django.urls import path
from . import views

app_name = 'rumah_sakit'

urlpatterns = [
    path('data-rumah-sakit/', views.dataRumahSakit, name='data-rumah-sakit'),
    path('data-rumah-sakit/add-rumah-sakit/', views.addRumahSakit, name='add-rumah-sakit'),
    path('data-rumah-sakit/detail-rumah-sakit/<int:pk>/', views.detailRumahSakit, name='detail-rumah-sakit'),
    path('data-rumah-sakit/remove-rumah-sakit/<int:pk>/', views.removeRumahSakit, name='remove-rumah-sakit'),
    path('data-rumah-sakit/search/', views.search, name='search'),
    path('data-rumah-sakit/add-rumah-sakit/create-rs/', views.createRS, name='create-rs'),
    ]

virus_pepew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pepew_home.urls')),
    path('donate/', include('donasi.urls')),
    path('', include('news.urls')),
    path('', include('question.urls')),
    path('', include('rumah_sakit.urls')),
    path('', include('screening.urls')),
]

rumah_sakit/models.py
from django.db import models

# Create your models here.
class RumahSakit(models.Model):

    PROVINSI= [ 
        ('Aceh', 'Aceh'),
        ('Sumatera Utara', 'Sumatera Utara'),
        ('Sumatera Barat', 'Sumatera Barat'),  
        ('Riau', 'Riau'),   
        ('Jambi', 'Jambi'),   
        ('Sumatera Selatan', 'Sumatera Selatan'), 
        ('Bengkulu', 'Bengkulu'),   
        ('Lampung', 'Lampung'),   
        ('Kep. Bangka Belitung', 'Kep. Bangka Belitung'),
        ('Kep. Riau', 'Kep. Riau'),
        ('DKI Jakarta', 'DKI Jakarta'),
        ('Jawa Barat', 'Jawa Barat'),
        ('Jawa Tengah', 'Jawa Tengah'),
        ('D.I. Yogyakarta', 'D.I. Yogyakarta'),
        ('Jawa Timur', 'Jawa Timur'),
        ('Banten', 'Banten'),
        ('Bali', 'Bali'),
        ('Nusa Tenggara Barat', 'Nusa Tenggara Barat'),
        ('Nusa Tenggara Timur', 'Nusa Tenggara Timur'),
        ('Kalimantan Barat', 'Kalimantan Barat'),
        ('Kalimantan Tengah', 'Kalimantan Tengah'),
        ('Kalimantan Selatan', 'Kalimantan Selatan'),
        ('Kalimantan Timur', 'Kalimantan Timur'),
        ('Kalimantan Utara', 'Kalimantan Utara'),
        ('Sulawesi Utara', 'Sulawesi Utara'),
        ('Sulawesi Tengah', 'Sulawesi Tengah'),
        ('Sulawesi Selatan', 'Sulawesi Selatan'),
        ('Sulawesi Tenggara', 'Sulawesi Tenggara'),
        ('Gorontalo', 'Gorontalo'),
        ('Sulawesi Barat', 'Sulawesi Barat'),
        ('Maluku', 'Maluku'),
        ('Maluku Utara', 'Maluku Utara'),
        ('Papua', 'Papua'),
        ('Papua Barat', 'Papua Barat')
    ]

    nama = models.CharField(max_length=50)
    alamat = models.TextField(max_length=200)
    provinsi = models.CharField(max_length=25, choices=PROVINSI)
    telepon = models.CharField(max_length=15)
    fax = models.CharField(max_length=15)

    def __str__(self):
        return self.nama

rumah_sakit/forms.py
from django.forms import ModelForm
from django import forms

from .models import RumahSakit

class AddRSForm(ModelForm):
    class Meta:
        model = RumahSakit
        fields = '__all__'
        
        labels = {
            'nama': 'Nama Rumah Sakit', 
            'alamat': 'Alamat',
            'provinsi': 'Provinsi', 
            'telepon': 'No Telepon', 
            'fax': 'Fax', 
        }

        widgets = {
            'nama': forms.TextInput({'class':'form-control'}),
            'alamat': forms.TextInput({'class':'form-control'}),
            'provinsi': forms.Select({'class':'form-control'}), 
            'telepon': forms.TextInput({'class':'form-control'}), 
            'fax': forms.TextInput({'class':'form-control'})
        }

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')  
        super(AddRSForm, self).__init__(*args, **kwargs)

rumah_sakit/views.py
from django.shortcuts import render, HttpResponseRedirect
from .models import RumahSakit
from .forms import AddRSForm
from django.contrib.auth.decorators import login_required
from django.core.serializers import serialize
import json
from django.http import JsonResponse

# Create your views here.
def dataRumahSakit(request):
    konteks = {
            'daftarRumahSakit': RumahSakit.objects.all()
        }
    return render(request, 'rumah_sakit/dataRumahSakit.html', konteks)

@login_required(login_url='news:login')
def addRumahSakit(request):
    konteks = {
            'form': AddRSForm()
        }
    return render(request, 'rumah_sakit/addRumahSakit.html', konteks)

def detailRumahSakit(request, pk):
    konteks = {
        'rumahSakit' : RumahSakit.objects.get(id=pk)
    }
    return render(request, 'rumah_sakit/detailRumahSakit.html', konteks)

@login_required(login_url='news:login')
def removeRumahSakit(request, pk):
    RumahSakit.objects.get(id=pk).delete()
    return HttpResponseRedirect('/data-rumah-sakit/')

def search(request):
    arg = request.GET['q']
    hasil = RumahSakit.objects.filter(nama__icontains=arg)
    data = serialize('json', hasil)
    return JsonResponse(json.loads(data), safe=False)

@login_required(login_url='news:login')
def createRS(request):
    message = []
    if request.method == 'POST':
        response = request.POST
        form = AddRSForm(response)
        if form.is_valid():
            form.save()
            message.append("Rumah sakit dengan nama \"" + response["nama"] + "\" berhasil ditambahkan")
        else:
            message.append("Input yang dimasukkan salah")
    return JsonResponse(message, safe=False)

rumah_sakit/templates/rumah_sakit/addRumahSakit.html
{% extends 'app-shell.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<title>Pepew | Tambah Data RS</title>
{% endblock meta%}

{% block content %}
<div class="content container-fluid c-birutua">
    <a class="btn bgc-birutua c-putih mb-5" href="{% url 'rumah_sakit:data-rumah-sakit' %}">
        <img class='small-icon' src="{% static 'img/arrowleft-icon.png' %}">Kembali
    </a>
    
    <h1 class="page-title ff-hanson ">Tambah Data Rumah Sakit</h1>    

    <div class="section bgc-birumuda">
        <form id="rs-form" method="POST">
            {% csrf_token %}
            {% for field in form %}
                <p class="form-label">{{ field.label }}</p>
                {{ field }}
            {% endfor %}
            <div class="text-center mt-4">
                <button type="submit" class="btn-default btn bgc-birutua c-putih">Tambah</button>
            </div>
        </form>
        <div class="message"></div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="{% static 'js/addRumahSakit.js' %}"></script>
{% endblock script %}

rumah_sakit/templates/rumah_sakit/dataRumahSakit.html
{% extends 'app-shell.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<title>Pepew | Daftar RS Rujukan</title>
{% endblock meta%}

{% block content %}
<div class="container-fluid py-5 header">
    <h1 id="title" class="ff-hanson c-birutua">Daftar<br>Rumah Sakit</h1>    
</div>

<div class="content container-fluid">
    <div class="d-flex flex-column flex-md-row align-content-center p-0">
        {% if user.is_authenticated %}
        <a class="btn bgc-birutua c-putih" href="{% url 'rumah_sakit:add-rumah-sakit' %}">
            <img class='small-icon' src="{% static 'img/plus-icon.png' %}">Tambah Rumah Sakit
        </a>
        {% endif %}
        <div id="show-search-box" class="btn bgc-birutua c-putih search-btn ml-md-auto mt-md-0">
            <i class="fa fa-search" aria-hidden="true"></i> Search
        </div>
        <div class="search-box align-content-center ml-md-auto mt-md-0">
            <span id="search-icon"><i class="fa fa-search" aria-hidden="true"></i></span>
            <input id="keyword" type="text" placeholder="Masukkan kata kunci">
            <div id="hide-search-box" class="d-inline-block btn p-0">
                <i class="fa fa-times" aria-hidden="true"></i>
            </div>
        </div>
    </div>
    
    
    <div class="wrapper  mt-4 bgc-birumuda c-birutua">
        <table id="list-rs" class="table mb-0">
            <thead>
                <tr class="c-putih bgc-birutua">
                    <th>No</th>
                    <th>Nama Rumah Sakit</th>
                    <th>Provinsi</th>
                </tr>
            </thead>
            <tbody id="rs">
                {% if daftarRumahSakit %}
                {% for rumahSakit in daftarRumahSakit %}
                <tr class="c-birutua bgc-birumuda">
                    <td>{{ forloop.counter }}</td>
                    <td><a class="link-detail c-birutua" href="{% url 'rumah_sakit:detail-rumah-sakit' rumahSakit.id %}">{{ rumahSakit }}</a></td>
                    <td>{{ rumahSakit.provinsi }}</td>
                </tr>
                {% endfor %}
                {% else %}
                <tr>
                    <td class="text-center" colspan="3">Tidak ada data rumah Sakit</td>
                </tr>
                {% endif %}
            </tbody>
        </table>
    </div>
    
</div>
{% endblock content %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script src="{% static 'js/dataRumahSakit.js' %}"></script>
{% endblock script %}

rumah_sakit/templates/rumah_sakit/detailRumahSakit.html
{% extends 'app-shell.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
<title>Pepew | Detail RS</title>
{% endblock meta%}

{% block content %}
<div class="content container-fluid">
    <a class="btn bgc-birutua c-putih mb-5" href="{% url 'rumah_sakit:data-rumah-sakit' %}">
        <img class='small-icon' src="{% static 'img/arrowleft-icon.png' %}">Kembali
    </a>

    <div class="page-title d-flex flex-column flex-md-row m-0">
        <h1 class="d-inline-block p-0 ff-hanson mr-5">{{rumahSakit.nama}}</h1>
        {% if user.is_authenticated %}
        <div class="ml-md-auto my-md-auto">
            <a class="btn bgc-birutua c-putih my-2" href="{% url 'rumah_sakit:remove-rumah-sakit' rumahSakit.id %}">
                Hapus
                <img class='small-icon icon-right' src="{% static 'img/x-icon.png' %}">
            </a>
        </div>
        {% endif %}
    </div>

    <div  class="section bgc-birumuda">
        <h4 class="font-weight-bold">Alamat</h4>
        <p>{{ rumahSakit.alamat }}</p>
        <h4 class="font-weight-bold">Provinsi</h4>
        <p>{{ rumahSakit.provinsi }}</p>
        <h4 class="font-weight-bold">Telepon</h4>
        <p>{{ rumahSakit.telepon }}</p>
        <h4 class="font-weight-bold">Fax</h4>
        <p>{{ rumahSakit.fax }}</p>
    </div>
</div>
{% endblock content %}