donasi/urls.py
from django.urls import path
from . import views

app_name = 'donasi'
urlpatterns = [
    path('', views.create, name='create'),
    path('payment/<str:username>.<int:payment_id>/', views.payment, name='payment'),
    path('list/', views.list_donate, name='list_donate'),
    path('feedback/', views.feedback, name='feedback')
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('list-news', views.news_list, name="news_list"),
    path('detail-news/<int:id>', views.news_detail, name="news_detail"),
    path('create-news', views.news_create, name="news_create"),
    path('data-news', views.news_data, name="news_data"),
    path('submission-news', views.news_submission, name="news_submission"),
    path('detail/news/<int:id>', views.news_get_detail, name="news_get_detail"),
    path('login-pepew', views.loginPage, name="login"),
    path('register-pepew', views.registerPage, name="register"),
    path('logout-pepew', views.logoutUser, name="logout"),
]

pepew_home/urls.py
from django.urls import path
from . import views


app_name = 'pepew_home'
urlpatterns = [
    path('', views.home_view, name="home_url"),
]

question/urls.py
from django.urls import path
from . import views

app_name = 'question'
urlpatterns = [
    path('question', views.create, name='create'),
    path('list/', views.list_question, name='list_question'),
]

rumah_sakit/urls.py
from django.urls import path
from . import views

app_name = 'rumah_sakit'

urlpatterns = [
    path('data-rumah-sakit/', views.dataRumahSakit, name='data-rumah-sakit'),
    path('data-rumah-sakit/add-rumah-sakit/', views.addRumahSakit, name='add-rumah-sakit'),
    path('data-rumah-sakit/detail-rumah-sakit/<int:pk>/', views.detailRumahSakit, name='detail-rumah-sakit'),
    path('data-rumah-sakit/remove-rumah-sakit/<int:pk>/', views.removeRumahSakit, name='remove-rumah-sakit'),
    path('data-rumah-sakit/search/', views.search, name='search'),
    path('data-rumah-sakit/add-rumah-sakit/create-rs/', views.createRS, name='create-rs'),
    ]

virus_pepew/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pepew_home.urls')),
    path('donate/', include('donasi.urls')),
    path('', include('news.urls')),
    path('', include('question.urls')),
    path('', include('rumah_sakit.urls')),
    path('', include('screening.urls')),
]

pepew_home/models.py
from django.db import models

# Create your models here.

pepew_home/views.py
from django.shortcuts import render

# Create your views here.
def home_view(request):
	return render(request, "pages/home.html")

pepew_home/templates/app-shell.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'images/pepew-icon.png' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <script src="https://kit.fontawesome.com/7ee84e11dc.js" crossorigin="anonymous"></script>
    {% block meta %}
    {% endblock meta %}
</head>
<body>
    <header>
        <div id="header-brand">
            <a href="{% url 'pepew_home:home_url' %}"><h1>Virus Pepew</h1></a>
            <div>
                {% if user.is_authenticated %}
                    <a href="{% url 'news:logout' %}"><i class="fas fa-sign-out-alt"></i>Logout</a>
                {% else %}
                    <a href="{% url 'news:register' %}"><i class="fas fa-user-plus"></i>Sign Up</a>
                    <a href="{% url 'news:login' %}"><i class="fas fa-sign-in-alt"></i>Login</a>
                {% endif %}
            </div>
        </div>
    
        <nav class="navbar navbar-expand-lg">
            <button class="navbar-toggler toggler-example" type="button" data-toggle="collapse" data-target="#navbarMenu"><i class="fas fa-bars fa-1x"></i></button>
            <div class="collapse navbar-collapse" id="navbarMenu">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'news:news_list' %}">Berita</a>
                    </li>
					<li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            QnA
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'question:create' %}">Form</a>
                            <a class="dropdown-item" href="{% url 'question:list_question' %}">List</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'rumah_sakit:data-rumah-sakit' %}">Daftar RS</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/Screening">Screening</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Donasi
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url 'donasi:create' %}">Form</a>
                            <a class="dropdown-item" href="{% url 'donasi:list_donate' %}">List</a>
                            <a class="dropdown-item" href="{% url 'donasi:feedback' %}">Feedback</a>
                        </div>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}
    
    <footer>
        <div id="info">
            <p>Kelompok E03 - PPW</p>
            <p>©Copyright 2020. All Rights Reserved</p>
        </div>
        <div id="hotline">
            <div id="call-info">
                <img src="{% static 'images/call-icon.png' %}">
                <h2>119</h2>
            </div>
            <p>Covid-19 HOTLINE</p>
        </div>
    </footer>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {% block script %}
    {% endblock script %}
</body>
</html>